### ISSUE TITLE
Eraser

### ISSUE THREAD

**Issue by mohamed-adly** [alnitak/finger_painter#1]
Hello!
how to implement eraser brush?
- there is no background

**Comment by alnitak** [comment]
Hi,
you can achieve that with PainterController().setBlendMode(ui.BlendMode.dstOut );

You can look at [here](https://api.flutter.dev/flutter/dart-ui/BlendMode.html) to see other blending modes

**Comment by mohamed-adly** [comment]
Yeah tried that but it draws a black lined before clearing the pixels.
i pulled the source and added Eraser pen that has the effect i need 
` @override
  onPointerDown(PointerDownEvent event) {
    drawing.points.clear();
    drawing.path.reset();

    drawing.points.add(event.localPosition);
    drawing.path.moveTo(event.localPosition.dx, event.localPosition.dy);
    painter = _Painter();
  }

  @override
  onPointerMove(PointerMoveEvent event) {
    drawing.points.add(event.localPosition);
    drawing.path.lineTo(event.localPosition.dx, event.localPosition.dy);

    painter = _Painter(
      andSaveImage: true,
      onImageSaved: onImageSaved != null
          ? (imgBytesList) => onImageSaved!(imgBytesList)
          : null,
    );
  }`
it comes with performance penalty, but in acceptable range for me

**Comment by iliyami** [comment]
> Hi, you can achieve that with PainterController().setBlendMode(ui.BlendMode.dstOut );
> 
> You can look at [here](https://api.flutter.dev/flutter/dart-ui/BlendMode.html) to see other blending modes

This solution draws a black lined before clearing the pixels. Is there any fix for it?
