### ISSUE TITLE
PainterController's method getPoints() always returns zero length list

### ISSUE THREAD

**Issue by petro-i** [alnitak/finger_painter#2]
Hi

Thank you for the great package, it is easy to use and flexible.

Could you please explain me how to use  getPoints() method in PainterController? 
It looks like what ever I paint it always returns zero length list. It could be misunderstanding from my side or a bug )).

**Comment by alnitak** [comment]
Hi and thanks for your report!

It was a bug, I was clearing the points list before firing the ```onDrawingEnded``` callback.
You can now get the points list like here:
```dart
Painter(
    controller: painterController,
    onDrawingEnded: (bytes) async {
      List<Offset>? points = painterController.getPoints();
    },
    ...
)
```
