### ISSUE TITLE
How to use setBitmapBackgroundColor method properly?

### ISSUE THREAD

**Issue by burcus** [alnitak/finger_painter#3]
Hi,
Thanks for this useful package. I checked the package codes in detail. I've knowledge it's working flow. But I haven't achieved to what I want to do. I want to show transparent canvas on my image (Default package usage can do this). But I want to different image color in my output image. When I get imageBytes() it's background is always transparent. I use setBitmapBackgroundColor func to do it, it was throwing an casting error then I fixed this issue. But still I can't achieve to my use case. Where should I set the bitmapBackgroundColor image and also is this function is proper to this use case?

**Comment by alnitak** [comment]
Hi,
thanks to you for the feedback!
Hope I have understand well your point: there was no way to set initial bitmap background color.
You are right, it was by default set to transparent. For this purpose I have just added a clear color parameter to ```PainterController.clearContent()```. See in the example [here](https://github.com/alnitak/finger_painter/blob/ee5ee70163d84ae6a64ce7bf316945943f56a966/example/lib/main.dart#L181).

You can now paint over using your background color and imageBytes() should return the correct image (I didn't tried but it should :) ).
I have already updated the repo, let me know!

**Comment by burcus** [comment]
@alnitak Thanks for your quick response, this isn't what I want. But I found a tricky solution for my issue and thanks again.
